### ISSUE TITLE
Iteration 1: Dashboard

### ISSUE THREAD

**Issue by thaomonster** [gaj23/fitlit-starter-kit#8]
DUE 12/9

- Use the `scripts.js` file to add information to the DOM. 
- **NOTE**: This file should call methods from your classes to retrieve information. There SHOULD NOT be any DOM manipulation within the `User` or `UserRepository` class files

To develop this dashboard, first choose a random user, then on the dashboard for the user
- [x] create info card with all of the user's info on the page
- [x] Display their first name somewhere prominently on the page to welcome them
- [x] For a specific user, display how their step goal compares to the average step goal amongst all users (this displayed should *not* be hard-coded)

**Comment by gaj23** [comment]
info to be displayed 
- [ ] current water intake
- [ ] hours slept
- [ ] current steps taken

**Comment by gaj23** [comment]
- [x] Increase font size of paragraph for step goals
